name: Code quality
description: Lints, type checks, and checks formatting

runs:
  using: "composite"

  steps:
    - name: Run type check
      run: npm run type-check
      shell: bash

    - name: Run linter
      run: npm run lint
      shell: bash

    - name: Check formatting
      run: npm run format:check
      shell: bash
