/* eslint-disable @typescript-eslint/no-empty-object-type */
import type { Knex } from 'knex';
import type { BaseAuditRows } from '../../database/types/tables.js';

type AutoGeneratedFields = 'id' | 'updated_at' | 'created_at';

/** Primary key type (can be string, integer or uuid) */
export type PrimaryKey = string | number;

export type CompositeKey = Record<string, PrimaryKey>;

export interface BaseEntity<ID extends PrimaryKey = PrimaryKey> extends BaseAuditRows {
  id: ID;
}

/** Entity with composite primary key - no single id field */
export interface CompositeKeyEntity extends BaseAuditRows {
  // No id field - entity is identified by combination of fields
}

/** Interface for entities with soft delete flag */
export interface SoftDeletableEntity<ID extends PrimaryKey = PrimaryKey> extends BaseEntity<ID> {
  deleted_at: Date | null;
}

/** Interface for entities with activate flag */
export interface ActivatableEntity<ID extends PrimaryKey = PrimaryKey> extends BaseEntity<ID> {
  is_active: boolean;
}

export interface TransactionContext {
  trx?: Knex.Transaction;
}

/** Query options for filtering records */
export interface QueryOptions extends TransactionContext {
  includeDeleted?: boolean;
  includeInactive?: boolean;
}

export interface GetManyOptions extends QueryOptions {
  limit?: number;
  offset?: number;
  // eslint-disable-next-line @typescript-eslint/array-type
  orderBy?: Array<{ column: string; order?: 'asc' | 'desc' }>;
}

export interface CreateOptions extends TransactionContext {}
export interface UpdateOptions extends TransactionContext {}
export interface DeleteOptions extends TransactionContext {}

/** Excludes auto-generated fields */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type InsertData<T extends BaseEntity<any> | CompositeKeyEntity> =
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  T extends BaseEntity<any> ? Omit<T, AutoGeneratedFields> : Omit<T, 'updated_at' | 'created_at'>;

/** Excludes auto-generated fields */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type UpdateData<T extends BaseEntity<any> | CompositeKeyEntity> =
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  T extends BaseEntity<any>
    ? Partial<Omit<T, AutoGeneratedFields>>
    : Partial<Omit<T, 'updated_at' | 'created_at'>>;

export type Where<T> = Partial<T>;

/** Base DAO methods that all classes must have */
export interface IBaseDAO<T extends BaseEntity<ID>, ID extends PrimaryKey = PrimaryKey> {
  create(data: InsertData<T>, options?: CreateOptions): Promise<T>;
  createMany(data: InsertData<T>[], options?: CreateOptions): Promise<T[]>;

  getById(id: ID, options?: QueryOptions): Promise<T | null>;
  getByManyIds(ids: ID[], options?: QueryOptions): Promise<T[]>;
  getOne(criteria: Where<T>, options?: QueryOptions): Promise<T | null>;
  getMany(criteria: Where<T>, options?: GetManyOptions): Promise<T[]>;
  getAll(options?: GetManyOptions): Promise<T[]>;
  exists(id: ID, options?: QueryOptions): Promise<boolean>;
  count(criteria?: Where<T>, options?: QueryOptions): Promise<number>;

  update(criteria: Where<T>, data: UpdateData<T>, options?: UpdateOptions): Promise<boolean>;
  updateMany(criteria: Where<T>, data: UpdateData<T>, options?: UpdateOptions): Promise<number>;
}

export interface ICompositeKeyDAO<T extends CompositeKeyEntity> {
  create(data: InsertData<T>, options?: CreateOptions): Promise<T>;
  createMany(data: InsertData<T>[], options?: CreateOptions): Promise<T[]>;

  getOne(criteria: Where<T>, options?: QueryOptions): Promise<T | null>;
  getMany(criteria: Where<T>, options?: GetManyOptions): Promise<T[]>;
  getAll(options?: GetManyOptions): Promise<T[]>;
  exists(criteria: Where<T>, options?: QueryOptions): Promise<boolean>;
  count(criteria?: Where<T>, options?: QueryOptions): Promise<number>;

  update(criteria: Where<T>, data: UpdateData<T>, options?: UpdateOptions): Promise<boolean>;
  updateMany(criteria: Where<T>, data: UpdateData<T>, options?: UpdateOptions): Promise<number>;
  delete(criteria: Where<T>, options?: DeleteOptions): Promise<boolean>;
}

/** Interface for base dao needing delete reversal methods */
export interface SoftDeleteMethods<T extends BaseEntity<ID>, ID extends PrimaryKey = PrimaryKey> {
  delete(id: ID, options?: DeleteOptions): Promise<boolean>;
  deleteMany(criteria: Where<T>, options?: DeleteOptions): Promise<boolean>;
  restore(id: ID, options?: UpdateOptions): Promise<T | null>;
  restoreMany(criteria: Where<T>, options?: UpdateOptions): Promise<number>;
}

/** Interface for base dao needing active flag toggling methods */
export interface ActivationMethods<T extends BaseEntity<ID>, ID extends PrimaryKey = PrimaryKey> {
  activate(id: ID, options?: UpdateOptions): Promise<T | null>;
  deactivate(id: ID, options?: UpdateOptions): Promise<T | null>;
}

export interface ISoftDeletableDAO<
  T extends SoftDeletableEntity<ID>,
  ID extends PrimaryKey = PrimaryKey,
>
  extends IBaseDAO<T, ID>, SoftDeleteMethods<T, ID> {}

export interface IActivatableDAO<
  T extends ActivatableEntity<ID>,
  ID extends PrimaryKey = PrimaryKey,
>
  extends IBaseDAO<T, ID>, ActivationMethods<T, ID> {}

export interface TableConfig {
  tableName: string;
  primaryKey: string;
  hasSoftDelete?: boolean;
  hasActivation?: boolean;
}

export interface CompositeKeyTableConfig {
  tableName: string;
  /** Array of column names that form the composite key */
  compositeKeys: string[];
  hasSoftDelete?: boolean;
  hasActivation?: boolean;
}
